feat: key not from file
makarski/rust_google_oauth2 pull request #29
Opened 2024-04-18 20:08 UTC by chris13524

This adds support for constructing a `ServiceAccount` directly from a `ServiceAccountKey`, rather than from a file. It also:
- Adds interior mutability using a tokio `RwLock` to enable cloning `ServiceAccount` while re-using the current access token across threads/instances. Also allows `ServiceAccount` to be used without needing to be `mut`.
- Makes `ServiceAccountKey` and its fields public to allow parsing or constructing the struct from any source (e.g. string, bytes, etc.) and also allows the fields inside to be re-used by other modules (e.g. reading `project_id` necessary for FCM)
- Adds `ServiceAccountBuilder` to enable the use of a variety of constructors, including the ability to re-use `reqwest::Client` across instantiations which enables sharing connection pools. Existing `from_file()` and `user_email()` methods continue to work for backwards-compatibility, but the builder pattern is generally a better alternative
- `access_token()` now returns `AccessToken` instead of e.g. `"Bearer token"` which allows the use of reqwest's `.bearer_token()` method without needing to parse-out the token. Also enables the invoker to see when the token will expire.
- Asserts that the returned token is indeed a bearer token
- `from_file()` retained as a helper method and now returns a `Result` type since file reading and parsing is performed in this function, rather than lazily in `access_token()`. Also now accepts any path-compatible value, rather than just `&str`.
- Stores `RsaKeyPair` in `JwtToken` rather than inputs to improve efficiency
- Catch and re-throw any non-200 status codes when requesting an access token. Also generally improve error handling by returning the original error, rather than converting into a string.
- Resolves various clippy errors

Resolves #28

2024-04-20 11:57 UTC, makarski requested changes
Hey @chris13524. Thanks for the PR. I managed to spot a few minor things, hope this is not too much of a hustle to do the changes. Also would be great to bump up the version in Cargo to `0.9`, since there is a breaking change to `access_token` return type.

2024-04-20 11:57 UTC, makarski commented on src/serv_account/errors.rs
> +    HttpRequestUnsuccessful(StatusCode, std::result::Result<String, reqwest::Error>),
std::result::Result could be shorted to StdResult, since there is already an import on line 3

2024-04-20 11:57 UTC, makarski commented on src/serv_account/errors.rs
> +    AccessTokenNotBeaarer(String),
Looks like there is a typo in Bea`a`rer

2024-04-20 11:57 UTC, makarski commented on src/serv_account/mod.rs
> +        const LEEWAY: Duration = Duration::seconds(30);
This piece seems not to compile for me. Here is the error message that I am get
```
error[E0015]: cannot call non-const fn `chrono::Duration::seconds` in constants
   --> src/serv_account/mod.rs:108:34
    |
108 |         const LEEWAY: Duration = Duration::seconds(30);
    |                                  ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: calls in constants are limited to constant functions, tuple structs and tuple variants
    ```

2024-04-20 11:57 UTC, makarski commented on src/serv_account/mod.rs
> +        let expires_at = Utc::now() + Duration::seconds(json.expires_in) - LEEWAY;
One of the options to resolve the issue with Duration above would be to keep it simple and use ints: 
`Utc::now().timestamp() as u64 + json.expires_in - 30`

2024-04-23 02:34 UTC, chris13524 commented
Thanks for the review! I'm working on some fixes for the above as well as some other tweaks

2025-02-25 11:21 UTC, makarski commented
@chris13524 should we close this one? I liked the idea - should we try finishing this?

2025-02-25 18:30 UTC, chris13524 commented
@makarski unfortunately I don't really have the bandwidth/focus from my company to revisit and properly upstream these changes. We are just happy with using the fork for now.

2026-06-02 09:19 UTC, makarski commented
Thanks for the draft, @chris13524 — and apologies for the long latency. The use case from #28 was eventually addressed in #31 (merged), which adds `ServiceAccount::from_bytes(&[u8], Vec<&str>)` and `JwtToken::from_bytes(&[u8])` so callers can pass key JSON directly. Closing this PR in favor of that landed work. Issue #28 closed alongside.

2026-06-02 09:19 UTC, closed without merging